# Generated by Django 4.2.1 on 2023-05-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('newname', models.CharField(max_length=50)),
                ('image', models.URLField(max_length=400)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
