# Generated by Django 4.2.1 on 2023-06-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='contenido',
            field=models.CharField(default='contenido nuevo', max_length=200),
            preserve_default=False,
        ),
    ]
