# Generated by Django 4.2.1 on 2023-06-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hoteles', '0003_hoteles_visitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteles',
            name='reservas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
