# Generated by Django 4.2.1 on 2023-06-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hoteles', '0004_hoteles_reservas'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteles',
            name='urls',
            field=models.CharField(default='ejemplo.com', max_length=200),
            preserve_default=False,
        ),
    ]
